TransparentPath/buildly-core

buildly/management/commands/loadinitialdata.py
buildly/tests/test_loadinitialdata.py

Oauth Application creation to be removed from Initial scripts
Code removal from the script

Changes for Oauth in Initial Script

---

gateway/views.py

_Short description of the problem or feature_
_How does this change address the problem?_

To solve issue as "OPTIONS" method for service not giving response from buildly core

---

core/serializers.py
core/views/coreuser.py
templates/email/coreuser/shipment_alert.html
templates/email/coreuser/shipment_alert.txt

This PR is for  Emails that user receives as alert message regarding his shipment

Email alert message for shipment to user

---

core/serializers.py
core/tests/test_coreuserview.py
core/tests/test_serializers.py

added email_alert_flag to CoreUser Serializer

fix added email_alert_flag to CoreUser Serializer

---

core/serializers.py
core/views/coreuser.py
templates/email/coreuser/shipment_alert.html

_Added support for multiple email alerts_

Added support for multiple email alerts

---

core/serializers.py
core/tests/test_serializers.py
core/views/coreuser.py
core/views/organization.py
gateway/clients.py
requirements/base.txt

Fetch Already existing Organizations in Buildly Core, Any logged in user can access this endpoint.

Fetch Already existing Organizations in Buildly Core

---

core/admin.py
core/serializers.py
core/views/coreuser.py

Update email alert endpoint to accept organization uuid, and send an email alert to respective associated users
Change the request for of email alert endpoint and change send email function as per request

change in request format of email alert endpoint

---

core/serializers.py
core/tests/test_organizationview.py
core/views/organization.py

_Organization names coming from open API as list of names_
Ticket number: #58 
closing #58
@vishalajackus @RadhikaPPatel

Organization names coming from open API as list of names

---

core/views/coreuser.py
templates/email/coreuser/shipment_alert.html

_Email Templates for Shipment Alerts_
Ticket number: #59 
closing #59
@vishalajackus @RadhikaPPatel

Email Templates for Shipment Alerts

---

core/views/organization.py

Make "/organization/fetch_orgs/" endoint open to everyone.
Add permission class to the function which fetches organization details.

Resolve permission issue for "/organization/fetch_orgs/" endpoint

---

buildly/management/commands/loadinitialdata.py
core/serializers.py
core/views/coreuser.py
templates/email/coreuser/shipment_alert.html

Modifications in email templates and sending out email as per user preferences
Ticket number: #76
closing #76

Modifications in email templates

---

core/views/consortium.py
core/views/coreuser.py

Change permission level for consortium table
Add permission level in permission class

Change permission level for consortium table

---

core/views/consortium.py

Filter consortium table by organization uuid
Write code views

filter consortium by organization

---

core/views/consortium.py

_Allow consortiums list to be accessed by any authenticated user and other endpoints only by a super admin_
_Helps front end to get a list of consortiums and filter other corresponding items_
Ticket number: #84 
closing #84

Changed permission level for consortium

---

gateway/request.py

When the request is for custody from custodian service for POST method,
it will create a consortium table in the core.
Check if URL is from custodian service for custody with POST method without join,
on success, implement functionality to create a consortium.

create consortium if custody create

---

requirements/base.txt

_Allows logic modules to function correctly_
Ticket number: #94 
@mthombare 
closing #94

Updated Bravado Core version

---

gateway/clients.py
requirements/base.txt
scripts/docker-entrypoint.sh

Return response data only for PUT, POST, DELETE
Ticket number: #96 
closing #96 
@mthombare

Return response data only for PUT, POST, DELETE

---

buildly/gunicorn_conf.py
scripts/docker-entrypoint.sh
scripts/run-standalone-dev.sh

_Add gunicorn config to process request sizes_
_Causing problem when fetching data for FTNW organization_
Ticket number:  #101 
@abhishek-kumar-piyush

Added Gunicorn config

---

core/views/coreuser.py

Show warning timezone with respect to user's timezone.
Change warning timezone to user's timezone only when user has timezone specified otherwise show UTC timezone.
Ticket number: [#191](https://github.com/TransparentPath/sensor_service/issues/191)
@yasmin2496

Environmental warning timezone.

---

Dockerfile
buildly/settings/base.py
core/serializers.py
docker-compose.yml

Changes for unit of measurements
Whenever a new organization is created, related unit of measurements must be created.
Ticket number: NA

Changes for unit of measurements
